name: angel
description: An easily-extensible web server framework in Dart.
version: 1.0.0-dev
author: thosakwe <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel
publish_to: none
dependencies:
  angel_auth: ">=1.0.0-dev <2.0.0"
  angel_configuration: ">=1.0.0-dev <2.0.0"
  angel_framework: ">=1.0.0-dev <2.0.0"
  angel_mongo: ">=1.0.0-dev <2.0.0"
  angel_mustache: ">=1.0.0-dev <2.0.0"
  angel_static: ">=1.0.0 <1.1.0"
  angular2: 2.0.0-beta.18
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  googleapis: ^0.30.1
  googleapis_auth: ^0.2.3
  json_god: ">=2.0.0-beta <3.0.0"
  money: ^0.1.5
  paypal_rest_api:
    path: ../paypal_dart
dev_dependencies:
  http: ">=0.11.3 <0.12.0"
  test: ">=0.12.13 <0.13.0"
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter